---
- hosts: controller
  tasks:
    - name: database parameters
      debconf: name='mariadb-server' question='mysql-server/{{item}}' value='root' vtype='password'
      with_items:
        - root_password
        - root_password_again
    - name: install packages
      apt: name={{item}}  state=present
      with_items: 
        - mariadb-server
        - python-mysqldb

    - name:
      template:
        src: /root/mysqlconfigure.conf.j2
        dest: /etc/mysql/conf.d/openstack.cnf
      tags:
        - dinesh
      notify: service restart

  handlers:
    - name: service restart
      service: name=mysql state=restarted
